[package]
name = "x86_rtc"
version = "0.1.1"
edition = "2021"
authors = ["Keyang Hu <keyang.hu@qq.com>"]
description = "System Real Time Clock (RTC) Drivers for x86_64 based on CMOS."
license = "GPL-3.0-or-later OR Apache-2.0 OR MulanPSL-2.0"
homepage = "https://github.com/arceos-org/arceos"
repository = "https://github.com/arceos-org/x86_rtc"
documentation = "https://docs.rs/x86_rtc"
keywords = ["arceos", "x86_64", "rtc"]
categories = ["os", "hardware-support", "no-std"]

[dependencies]
cfg-if = "1.0"

[dependencies.range_check]
# version = "0.2.0"
# path = "../rust-range-check"
git = "https://github.com/ChocolateLoverRaj/rust-range-check"
branch = "no-std"

[target.'cfg(target_arch = "x86_64")'.dependencies]
x86_64 = "0.15"
